#!/bin/dash

# Testing if the .shrug has already been created
if ! test -d ".shrug"
then
    # Creating new .shrug
    mkdir .shrug
    echo "Initialized empty shrug repository in .shrug"
else
    # .shrug already exists
    echo "shrug-init: error: .shrug already exists"
fi
