#!/bin/dash

# Obtaining current branch
current_branch=`cat .shrug/current_branch`

# Parsing user input
requested_commit=`echo $1 | cut -d":" -f1`
requested_file=`echo $1 | cut -d":" -f2`

# Checking request
if [ "$requested_commit" = "" ]
then
    # If no commit requested, provide index information
    # Checking validity of commit
    if ! test -e .shrug/branches/$current_branch/index/$requested_file
    then
        # File cannot be found
        echo "shrug-show: error: '$requested_file' not found in index"
    else
        # File can be found
        cat .shrug/branches/$current_branch/index/$requested_file
    fi
else
    # If commit details, provide file information
    # Checking if commit is valid
    if test -d .shrug/branches/$current_branch/$requested_commit
    then
        # Testing if the file exists
        if test -e .shrug/branches/$current_branch/$requested_commit/saved/$requested_file
        then
            # File exists
            cat .shrug/branches/$current_branch/$requested_commit/saved/$requested_file
        else
            # File does not exist
            echo "shrug-show: error: '$requested_file' not found in commit $requested_commit"
        fi
    else
        # Could not find directory containing file
        echo "shrug-show: error: unknown commit '$requested_commit'"
    fi
fi
