#!/bin/dash

# Obtaining current branch
current_branch=`cat .shrug/current_branch`

# Getting previous commit id
previous_commit_id=`ls .shrug/branches/$current_branch | sort -n | tail -1`
if [ $previous_commit_id = "index" ] || [ $previous_commit_id = "stash" ]
then
    previous_commit_id=0
fi

# Removing files given by the user
# Looping through all files given by user
for file in $@
do
    # Deleting file from index if it is not a keyword
    if [ $file != --force ] && [ $file != --cached ]
    then
        # Checking if the argument exists in the index
        if ! test -e .shrug/branches/$current_branch/index/$file
        then
            echo "shrug-rm: error: '$file' is not in the shrug repository"
            continue
        fi

        # Checking type of removal requested
        if [ $1 = --force ]
        then
            # Force removal requested - deleting no matter what
            if [ $2 != --cached ]
            then
                # Removing if cached option is not chosen
                rm $file 2> /dev/null
            fi

            # Removing, errors will be ignored
            rm .shrug/branches/$current_branch/index/$file 2> /dev/null
        elif [ $1 != --cached ]
        then
            # Normal deletion - files which have been edited upon are not deleted
            if [ $(diff $file .shrug/branches/$current_branch/index/$file | wc -l) != 0 ] && test -e .shrug/branches/$current_branch/$previous_commit_id/saved/$file && [ $(diff .shrug/branches/$current_branch/index/$file .shrug/branches/$current_branch/$previous_commit_id/saved/$file | wc -l) != 0 ]
            then
                # File is different from index to working to repository
                echo "shrug-rm: error: '$file' in index is different to both working file and repository"
            elif ! test -e .shrug/branches/$current_branch/$previous_commit_id/saved/$file || [ $(diff .shrug/branches/$current_branch/index/$file .shrug/branches/$current_branch/$previous_commit_id/saved/$file | wc -l) != 0 ]
            then
                # File in index has been edited since last commit
                echo "shrug-rm: error: '$file' has changes staged in the index"
            elif test -e .shrug/branches/$current_branch/$previous_commit_id/saved/$file && [ $(diff $file .shrug/branches/$current_branch/$previous_commit_id/saved/$file | wc -l) != 0 ]
            then
                # Working file is different to repository file
                echo "shrug-rm: error: '$file' in repository is different to working file"
            else
                # Successful deletion of files
                rm $file
                rm .shrug/branches/$current_branch/index/$file
            fi
        elif [ $1 = --cached ]
        then
            # Removing if the file is not different
            if [ $(diff $file .shrug/branches/$current_branch/index/$file | wc -l) != 0 ] && test -e .shrug/branches/$current_branch/$previous_commit_id/saved/$file && [ $(diff .shrug/branches/$current_branch/index/$file .shrug/branches/$current_branch/$previous_commit_id/saved/$file | wc -l) != 0 ]
            then
                # File in working file is different to index and repository
                echo "shrug-rm: error: '$file' in index is different to both working file and repository"
            else
                # Successfully deleting files
                rm .shrug/branches/$current_branch/index/$file
            fi
        fi
    fi
done
