#!/bin/dash

# Obtaining current branch
current_branch=`cat .shrug/current_branch`

# Getting all directories from most recent commit first
for commit in $(ls .shrug/branches/$current_branch -r)
do
    # If it is not the index file
    if [ $commit != "index" ]
    then
        # Print commit details
        echo -n "$commit "
        cat ".shrug/branches/$current_branch/$commit/message.txt"
    fi
done
