#!/bin/dash

# Checking .shrug exists
if test -d ".shrug"
then
    # .shrug exists
    # Obtaining current branch
    current_branch=`cat .shrug/current_branch`

    # Adding all files given in the argument
    for file in $@
    do
        if test -e $file
        then
            # Newly added file
            # Adding new file to the list to be added
            cp $file .shrug/branches/$current_branch/index/$file
        elif test -e .shrug/branches/$current_branch/index/$file
        then
            # File does not exist in working environment but exists in index
            # Deleting file
            rm .shrug/branches/$current_branch/index/$file
        else
            # Unsuccessfully added file
            echo "shrug-add: error: can not open '$file'"
        fi
    done
else
    # Cannot add files as .shrug does not exist
    echo "shrug-add: error: no .shrug directory containing shrug repository exists"
fi
