#!/bin/dash

new_items() {
    # Checking if it is a directory
    if test -d .shrug/$(($i - 1))
    then
        # Checking if there is a new file in index
        for new_file in .shrug/index/*
        do
            # Getting name of current file
            file=`echo $new_file | cut -d"/" -f3`

            # Checking if file exists
            if test -e ".shrug/$(($i - 1))/saved/$file"
            then
                # File exists, checking if there is a difference
                if [ $(diff $new_file ".shrug/$(($i - 1))/saved/$file" | wc -l ) != 0 ]
                then
                    return 1
                fi
            else
                # File does not exist, there are new items
                return 1
            fi
        done

        # Checking if there is a newly deleted file
        for new_file in .shrug/$(($i - 1))/saved/*
        do
            # Getting name of current file
            file=`echo $new_file | cut -d"/" -f4`

            # Checking if file exists
            if ! test -e ".shrug/index/$file"
            then
                # File got removed exists, checking if there is a difference
                return 1
            fi
        done

        # Could not find a new file
        return 0
    else
        # Directory does not exist
        return 1
    fi
}

# Getting latest commit id
i=0
while true
do
    if ! test -d ".shrug/$i"
    then
        break
    fi
    i=$(($i+1))
done

# Checking if it is a new commit or not
if [ $1 = "-a" ]
then
    # Requires committing all items
    for file in *
    do
        sh shrug-add $file
    done

    # Obtaining message
    message=$3
else
    # Obtaining message
    message=$2
fi

# # Checking if there are items to commit
new_items
if [ $? -eq "1" ]
then
    # Creating latest commit folder
    mkdir ".shrug/$i"

    # Saving files
    mkdir ".shrug/$i/saved"
    for line in $(ls .shrug/index)
    do
        cp .shrug/index/$line ".shrug/$i/saved/$line"
    done

    # Adding commit message
    echo $message > ".shrug/$i/message.txt"

    # Notifying user of completed commit
    echo Committed as commit $i

else
    echo nothing to commit
fi
