#!/bin/dash

if [ $# = 0 ]
then
    # Displaying all branches
    # Looping through all branches
    for branch in .shrug/branches/*
    do
        # Obtaining branch name
        branch=`echo $branch | cut -d"/" -f3`

        # Checking if there have been commits
        if ! test -d .shrug/branches/master/0
        then
            # Repository does not have any commits
            echo shrug-branch: error: your repository does not have any commits yet
        else
            # Printing branch
            echo $branch
        fi
    done
elif [ $1 = -d ]
then
    # Deleting branch
    if [ $2 = 'master' ]
    then
        # Cannot delete master
        echo "shrug-branch: error: can not delete branch '$2'"
    elif test -d .shrug/branches/$2
    then
        # Branch exists
        # Deleting branch
        rm -rf .shrug/branches/$2

        # Notifying user of deleted branch
        echo "Deleted branch '$2'"
    else
        # Branch does not exist
        echo "shrug-branch: error: branch '$2' does not exist"
    fi
else
    # Checking if the branch already exists
    if ! test -d .shrug/branches/$1
    then
        # Obtaining current branch
        current_branch=`cat .shrug/current_branch`

        # Creating new branch
        mkdir .shrug/branches/$1
        mkdir .shrug/branches/$1/index
        mkdir .shrug/branches/$1/stash
        cp -R .shrug/branches/$current_branch/* .shrug/branches/$1/ 2> /dev/null
    else
        # Branch already exists
        echo "shrug-branch: error: branch '$1' already exists"
    fi
fi
